### PR TITLE
Blacklist 3.23 gnome-settings-daemon rubbish from starting as it real…

### PR DESCRIPTION
**Pull request by leigh123linux**
…ly screws stuff up

### CODE REVIEW

**Comment by clefebvre** [comment]
Out of curiosity, how is it launched?

**Comment by leigh123linux** [comment]
They are autostarted by xdg

```
[leigh@localhost autostart]$ ls /etc/xdg/autostart/ |grep org.gnome
org.gnome.SettingsDaemon.A11yKeyboard.desktop
org.gnome.SettingsDaemon.A11ySettings.desktop
org.gnome.SettingsDaemon.Clipboard.desktop
org.gnome.SettingsDaemon.Color.desktop
org.gnome.SettingsDaemon.Datetime.desktop
org.gnome.SettingsDaemon.Housekeeping.desktop
org.gnome.SettingsDaemon.Keyboard.desktop
org.gnome.SettingsDaemon.MediaKeys.desktop
org.gnome.SettingsDaemon.Mouse.desktop
org.gnome.SettingsDaemon.Orientation.desktop
org.gnome.SettingsDaemon.Power.desktop
org.gnome.SettingsDaemon.PrintNotifications.desktop
org.gnome.SettingsDaemon.Rfkill.desktop
org.gnome.SettingsDaemon.ScreensaverProxy.desktop
org.gnome.SettingsDaemon.Sharing.desktop
org.gnome.SettingsDaemon.Smartcard.desktop
org.gnome.SettingsDaemon.Sound.desktop
org.gnome.SettingsDaemon.Wacom.desktop
org.gnome.SettingsDaemon.XRANDR.desktop
org.gnome.SettingsDaemon.XSettings.desktop
[leigh@localhost autostart]$ cat org.gnome.SettingsDaemon.XSettings.desktop
[Desktop Entry]
Type=Application
Name=GNOME Settings Daemon's xsettings plugin
Exec=/usr/libexec/gsd-xsettings
OnlyShowIn=GNOME;
NoDisplay=true
X-GNOME-Autostart-Phase=Initialization
X-GNOME-Autostart-Notify=true
X-GNOME-AutoRestart=true
[leigh@localhost autostart]$
```

**Comment by clefebvre** [comment]
Hmm.. maybe it's time we review the reason why we launch GNOME services, and if we still need to do so, maybe we should support widcards in the blacklist... it seems tedious to list them all like that, it would only be a matter of time before another plugin is added upstream.

**Comment by itzexor** [comment]
It may already work this way. Did you try just adding `org.gnome.SettingsDaemon`?

https://github.com/linuxmint/cinnamon-session/blob/master/cinnamon-session/csm-manager.c#L4145
https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strrstr-len

**Pull request closed without merging**
