### PR TITLE
Improve debian packaging

### PR DESCRIPTION
**Pull request by Fantu**

### CODE REVIEW

**Comment by clefebvre** [comment]
default-dbus-session-bus | dbus-session-bus

None of these exist here.

**Comment by Fantu** [comment]
@clefebvre https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835844
you can find them in Provides field of debian/control of packages like dbus-user-session and dbus-x11

**Comment by Fantu** [comment]
@clefebvre rebased, if you still needed support system older that stretch/bionic don't apply  "switch from dbus-x11 to default-dbus-session-bus | dbus-session-bus" commit

**Comment by Fantu** [comment]
the fails of lmde3 test build seems strange because some days ago I built and tested (update and use) debian packages on stretch including these changes without issue:
http://debomatic-amd64.debian.net/distribution#dpr-cinnamon-stretch-backports/cinnamon-session/3.6.0-1~

**Comment by Fantu** [comment]
now that I had confirm of mint18 support dropped I added other improvements, I also tested build on stretch:
http://debomatic-amd64.debian.net/distribution#dpr-lmde-stable/cinnamon-session/3.7.0~

**Comment by Fantu** [comment]
I you want consider this PR in these day exclude commits from first circleci I'm using for some fast testing about trying improving it

**Comment by Fantu** [comment]
@clefebvre checking build after rebase I spotted that with meson without debhelper some files changed from /usr/lib/x86_64-linux-gnu/ to /usr/lib/cinnamon-session/
I think is another unexpected case like nemo (build not failed because .install still take it)
Now I'll try to solves also it without debhelper 11

**Pull request merged**
